In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [2]:
data=pd.read_csv("C://Users//ashok//Desktop//UIC//spring 2020//python 400//a7//bank.csv",sep=';')
data.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

In [3]:
for name, dtype in data.dtypes.iteritems():
    print(name, dtype)

age int64
job object
marital object
education object
default object
balance int64
housing object
loan object
contact object
day int64
month object
duration int64
campaign int64
pdays int64
previous int64
poutcome object
y object


In [4]:
data['y'].value_counts()

no     4000
yes     521
Name: y, dtype: int64

In [5]:
data.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [6]:
#replacing 'loan','housing','education' and 'marital' categories with 0,1,2
data1=data.replace({'loan':{'yes':1}})
data2=data1.replace({'loan':{'no':0}})
data3=data2.replace({'marital':{'single':0}})
data4=data3.replace({'marital':{'married':1}})
data5=data4.replace({'marital':{'divorced':2}})
data6=data5.replace({'housing':{'yes':1}})
data7=data6.replace({'housing':{'no':0}})
data8=data7.replace({'education':{'primary':0}})
data9=data8.replace({'education':{'unknown':0}})
data10=data9.replace({'education':{'secondary':1}})
data11=data10.replace({'education':{'tertiary':2}})
data12=data11.replace({'default':{'yes':1}})
data13=data12.replace({'default':{'no':0}})
data14=data13.replace({'pdays':{-1:0}})
data15=data14.replace({'y':{'yes':1}})
data16=data15.replace({'y':{'no':0}})
data16.head()

age          job  marital  education  default  balance  housing  loan  \
0   30   unemployed        1          0        0     1787        0     0   
1   33     services        1          1        0     4789        1     1   
2   35   management        0          2        0     1350        1     0   
3   30   management        1          2        0     1476        1     1   
4   59  blue-collar        1          1        0        0        1     0   

    contact  day month  duration  campaign  pdays  previous poutcome  y  
0  cellular   19   oct        79         1      0         0  unknown  0  
1  cellular   11   may       220         1    339         4  failure  0  
2  cellular   16   apr       185         1    330         1  failure  0  
3   unknown    3   jun       199         4      0         0  unknown  0  
4   unknown    5   may       226         1      0         0  unknown  0

In [7]:
data16['y'].value_counts()

0    4000
1     521
Name: y, dtype: int64

In [8]:
X_data16 = data16[['marital', 'education', 'default', 'housing', 'loan', 'duration', 'campaign', 'pdays']].copy()
Y_data16 = data16[['y']].copy()

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_data16, Y_data16, test_size=0.2, random_state=0)

In [10]:
y_train = np.ravel(y_train) 
y_test = np.ravel(y_test)

In [11]:
y_train.shape

(3616,)

In [12]:
#linear regression
reg = LinearDiscriminantAnalysis().fit(X_train, y_train)

In [13]:
#cross reference score
print(reg.score(X_test, y_test))

0.8883977900552487


In [14]:
#confusion matrix
reg_pred = reg.predict(X_test)
print(confusion_matrix(y_test, reg_pred))

[[764  29]
 [ 72  40]]


In [15]:
#logistic regression
logclf = LogisticRegression(random_state=0).fit(X_train, y_train)

In [16]:
#cross reference score
print(logclf.score(X_test, y_test))

0.8839779005524862


In [17]:
#confusion matrix
log_pred = logclf.predict(X_test)
print(confusion_matrix(y_test, log_pred))

[[774  19]
 [ 86  26]]


In [18]:
#Decision tree
DTclf = tree.DecisionTreeClassifier().fit(X_train, y_train)

In [19]:
#cross reference score
print(DTclf.score(X_test, y_test))

0.8331491712707182


In [20]:
#confusion matrix
DT_pred = DTclf.predict(X_test)
print(confusion_matrix(y_test, DT_pred))

[[712  81]
 [ 70  42]]


In [21]:
#KNN
Knnclf = KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train)

In [22]:
#cross reference score
print(Knnclf.score(X_test, y_test))

0.861878453038674


In [23]:
#confusion matrix
Knn_pred = Knnclf.predict(X_test)
print(confusion_matrix(y_test, Knn_pred))

[[745  48]
 [ 77  35]]


In [24]:
#SVM
svmclf=SVC(kernel='rbf',random_state=0).fit(X_train,y_train)

In [25]:
#cross reference score
print(svmclf.score(X_test, y_test))

0.8729281767955801


In [26]:
#confusion matrix
svm_pred = svmclf.predict(X_test)
print(confusion_matrix(y_test, svm_pred))

[[789   4]
 [111   1]]


In [27]:
print('logistic regression and SVM models give us the best cross reference score among the models we used for this data')

logistic regression and SVM models give us the best cross reference score among the models we used for this data
